server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka  ## 注册到 eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: single-customer
feign:
  hystrix:
    enabled: true